### ISSUE TITLE
Task 1a: Find 6 Artists 

### ISSUE THREAD

**Issue by evansuslovich** [evansuslovich/MoMA-ML#4]
Post Impressionist Artists! 

Paul Cezanne -- In folder

Vincent Van Gogh -- https://www.kaggle.com/datasets/ipythonx/van-gogh-paintings/data

Camille Pissarro -- In folder

Paul Gauguin -- In folder

Edvard Munch -- https://www.kaggle.com/datasets/isaienkov/edvard-munch-paintings/data

Edgar Degas -

**Comment by superhvarn** [comment]
Completed
